import type { Question } from "./quiz";

export const oilQuiz: Question[] = [
  { q: "What does BS&W stand for?", options: ["Basic Sediment & Water", "Best Sample Water", "Black Solids & Wax", "Brine Salt & Water"], answer: 0, explain: "BS&W = Basic Sediment & Water, the contamination level in crude oil." },
  { q: "Maximum BS&W typically allowed for crude oil export?", options: ["10%", "5%", "0.5%", "20%"], answer: 2, explain: "Most pipeline / tanker specs require BS&W below 0.5%." },
  { q: "A 3-phase separator separates…", options: ["Gas, oil and water", "Oil, water and sand", "Three different gases", "Hot, warm and cold streams"], answer: 0, explain: "Gas exits the top, oil the middle, water the bottom." },
  { q: "Pump cavitation is caused by…", options: ["Excess discharge head", "Vapour forming at the impeller (low NPSH available)", "High motor current", "Closed discharge valve"], answer: 1, explain: "If suction pressure drops below the liquid's vapour pressure, vapour bubbles form and collapse on the impeller." },
  { q: "Typical symptom of pump cavitation?", options: ["Smooth quiet running", "Gravel-like noise and vibration", "Reduced motor current", "Higher efficiency"], answer: 1, explain: "Imploding vapour bubbles create a characteristic gravel-rattling noise." },
  { q: "LMTD in heat exchanger design stands for…", options: ["Log Mean Temperature Difference", "Linear Mass Transfer Density", "Low Medium Thermal Duty", "Liquid Mass Transit Diameter"], answer: 0, explain: "LMTD is the effective driving temperature difference between hot and cold streams." },
  { q: "Heat exchanger duty equation?", options: ["Q = m·Cp", "Q = U·A·ΔT", "Q = U·A·LMTD", "Q = ρ·V"], answer: 2, explain: "Q = U·A·LMTD relates duty to area, overall heat transfer coefficient and LMTD." },
  { q: "Fouling in a shell-and-tube exchanger causes…", options: ["Higher duty", "Reduced U value and reduced duty", "Lower pressure drop", "Higher LMTD"], answer: 1, explain: "Fouling adds thermal resistance, dropping U and the duty." },
  { q: "An electrostatic dehydrator removes water by…", options: ["Boiling it off", "Coalescing water droplets in a high-voltage field", "Centrifugal force", "Chemical absorption only"], answer: 1, explain: "15-30 kV polarises droplets so they coalesce and settle out." },
  { q: "Produced water must be treated before sea discharge to…", options: ["Cool it down", "Reduce oil-in-water below regulatory limit (~40 ppm)", "Add chlorine", "Increase salinity"], answer: 1, explain: "OSPAR / similar regulations cap overboard oil-in-water around 40 ppm." },
  { q: "A centrifugal pump's Q-H curve shows…", options: ["Flow vs efficiency only", "Head vs flow", "Power vs RPM", "Pressure vs temperature"], answer: 1, explain: "Head decreases as flow increases on a centrifugal pump curve." },
  { q: "NPSH stands for…", options: ["Net Pump Suction Head", "Net Positive Suction Head", "Nominal Pressure Static Head", "Normal Process Surface Head"], answer: 1, explain: "NPSHa must exceed NPSHr to avoid cavitation." },
  { q: "A choke valve at the wellhead is used to…", options: ["Stop the well", "Reduce and control flowing pressure to downstream equipment", "Heat the fluid", "Measure flow"], answer: 1, explain: "Chokes drop pressure from reservoir conditions to facility design pressure." },
  { q: "Retention time in a 3-phase separator controls…", options: ["Pump efficiency", "Quality of phase separation (BS&W, oil-in-water)", "Compressor surge", "Tank vapour pressure"], answer: 1, explain: "Longer retention lets droplets coalesce and settle by gravity." },
  { q: "A floating roof tank is used mainly to…", options: ["Speed crude loading", "Reduce vapour losses and explosion risk", "Heat the crude", "Mix the contents"], answer: 1, explain: "The roof floats on the liquid, almost eliminating vapour space." },
  { q: "Pipeline corrosion is typically driven by…", options: ["Pure oil", "Water, CO₂ and H₂S (sour service)", "Inert gas", "High flow only"], answer: 1, explain: "Wet CO₂/H₂S environments produce carbonic / sulphidic corrosion." },
  { q: "An emulsion in a separator is best broken by…", options: ["Raising pressure", "Heat + retention + demulsifier chemical", "Closing the dump valve", "Adding water"], answer: 1, explain: "Thermal and chemical treatment plus residence time destabilise tight emulsions." },
  { q: "If pump suction pressure suddenly drops, you should first…", options: ["Open the discharge wider", "Reduce flow / check suction strainer & NPSH", "Increase RPM", "Ignore it"], answer: 1, explain: "Loss of NPSHa triggers cavitation; reduce demand and find the cause." },
  { q: "Water carry-over to oil export is dangerous because…", options: ["It cools the line", "It off-specs the crude and accelerates corrosion", "It raises pump efficiency", "It cleans the pipeline"], answer: 1, explain: "Water in export crude both fails BS&W spec and corrodes pipelines/tanks." },
  { q: "In a 3-phase separator, the oil level is normally controlled by…", options: ["The gas outlet PIC", "An LIC modulating the oil-draw valve", "Flow into the wellhead", "Ambient temperature"], answer: 1, explain: "A level controller (LIC) cascades to the oil outlet valve to hold a constant interface." },
];
