import type { Question } from "./quiz";

export const storageQuiz: Question[] = [
  { q: "What is the main purpose of a floating roof tank?", options: ["Faster filling", "Reduces vapor space and fire risk", "Insulates the crude", "Mixes the contents"], answer: 1, explain: "The roof floats on the liquid surface, almost eliminating vapor space and the fire/explosion risk it creates." },
  { q: "What is the purpose of a PSV?", options: ["Measure pressure", "Protect equipment from overpressure", "Boost pressure", "Cool the fluid"], answer: 1, explain: "A Pressure Safety Valve releases excess pressure to a safe location to protect vessels and piping." },
  { q: "What does fiscal metering mean?", options: ["Periodic maintenance check", "Custody transfer for commercial transactions", "Internal plant accounting", "Calibration of pressure sensors"], answer: 1, explain: "Fiscal (custody-transfer) metering is the legally-witnessed measurement used for buying and selling hydrocarbons." },
  { q: "Why are gas storage vessels spherical?", options: ["Easier to manufacture", "Sphere distributes pressure equally in all directions", "Better thermal insulation", "Cheaper than cylinders"], answer: 1, explain: "A sphere is the optimal shape for high-pressure storage — wall stress is uniform in every direction." },
  { q: "What is the danger of tank overfill?", options: ["Lower temperature", "Spill, fire hazard and environmental damage", "Increased viscosity", "Reduced export rate"], answer: 1, explain: "Overfill spills hydrocarbons to bund / environment with major fire and pollution consequences (e.g. Buncefield)." },
  { q: "What is pump cavitation?", options: ["Excess discharge head", "Vapor bubbles forming and collapsing on the impeller", "Motor overload", "Closed suction valve"], answer: 1, explain: "When local suction pressure falls below the liquid's vapour pressure, vapour bubbles form and collapse, eroding the impeller." },
  { q: "In a P&ID, the tag 'LV' stands for…", options: ["Low Voltage", "Level Valve (a level-control valve)", "Liquid Vent", "Local Vendor"], answer: 1, explain: "LV is the standard ISA tag for a level-control valve actuated by a level controller (LIC)." },
  { q: "Typical crude oil storage temperature?", options: ["10–20 °C", "40–60 °C to maintain flow properties", "100–120 °C", "Below freezing"], answer: 1, explain: "Crude is kept warm (typ. 40–60 °C) so viscosity stays low enough to pump and to keep waxes in solution." },
  { q: "What does BS&W mean for stored crude?", options: ["Boiling Steam & Water", "Basic Sediment and Water content", "Black Sulfur & Wax", "Bottom Salt & Water"], answer: 1, explain: "BS&W = Basic Sediment & Water — the non-oil contamination measured against export spec (typically < 0.5 %)." },
  { q: "What happens when a PSV opens?", options: ["The vessel is shut down", "Excess pressure is released to a safe location (flare/atm)", "The pump speeds up", "The level controller trips"], answer: 1, explain: "A PSV vents the relieving fluid to flare or safe atmosphere until pressure drops below the reseat point." },
  { q: "Ullage in tank gauging is…", options: ["The total stored volume", "The empty space above the liquid surface", "The water bottom", "The vapor pressure"], answer: 1, explain: "Ullage is the distance from the liquid surface to a fixed reference (usually the dip-hatch) — i.e. the empty space." },
  { q: "In a P&ID the tag 'XV' stands for…", options: ["Expansion Valve", "Emergency / on-off isolation valve", "Excess Vent", "External Vacuum"], answer: 1, explain: "XV is the ISA tag for an on-off shutdown valve, typically actuated by an SIS." },
  { q: "Why must a gas sphere never drop below its minimum pressure?", options: ["To save export revenue", "To prevent air ingress and an explosive mixture", "To stop corrosion", "To keep the sphere round"], answer: 1, explain: "If sphere pressure falls below atmospheric, air can enter and form an explosive fuel-air mixture inside." },
  { q: "What is the purpose of a crossover (tie) valve between tanks?", options: ["Drain water bottoms only", "Allow transfer between tanks for operational flexibility", "Vent the tanks", "Mix product grades"], answer: 1, explain: "Crossover valves let operators transfer inventory between tanks for blending, isolation or maintenance." },
  { q: "What does an LIC controller do in a storage tank?", options: ["Controls temperature by adjusting steam", "Controls liquid level by adjusting an outlet valve (LV)", "Measures flow", "Closes the PSV"], answer: 1, explain: "A Level Indicating Controller (LIC) cascades to an LV (level valve) to hold the tank at its set-point level." },
];
