/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OilRouteImport } from './routes/oil'
import { Route as GasRouteImport } from './routes/gas'
import { Route as IndexRouteImport } from './routes/index'

const OilRoute = OilRouteImport.update({
  id: '/oil',
  path: '/oil',
  getParentRoute: () => rootRouteImport,
} as any)
const GasRoute = GasRouteImport.update({
  id: '/gas',
  path: '/gas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gas': typeof GasRoute
  '/oil': typeof OilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gas': typeof GasRoute
  '/oil': typeof OilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gas': typeof GasRoute
  '/oil': typeof OilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gas' | '/oil'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gas' | '/oil'
  id: '__root__' | '/' | '/gas' | '/oil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GasRoute: typeof GasRoute
  OilRoute: typeof OilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/oil': {
      id: '/oil'
      path: '/oil'
      fullPath: '/oil'
      preLoaderRoute: typeof OilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gas': {
      id: '/gas'
      path: '/gas'
      fullPath: '/gas'
      preLoaderRoute: typeof GasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GasRoute: GasRoute,
  OilRoute: OilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
